spring.application.name=finnova-backend

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finnova_db
spring.datasource.username=postgres
spring.datasource.password=0819a6d7d204.Mr

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del backend
server.port=8080

# JWT
jwt.secret=finnova_clave_secreta_super_larga_para_firmar_tokens_2026_usal
jwt.expiration=86400000

# Envio de mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=olmedo.uriel01@gmail.com
spring.mail.password=ctsiuhaghdjvifhr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL del frontend, para armar el link del mail
app.frontend.url=http://localhost:5173