spring.application.name=finnova-backend

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finnova_db
spring.datasource.username=postgres
spring.datasource.password=0819a6d7d204.Mr

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del backend
server.port=8080